//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class schema_version
    {
        public int installed_rank { get; set; }
        public string version { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public string script { get; set; }
        public Nullable<int> checksum { get; set; }
        public string installed_by { get; set; }
        public System.DateTime installed_on { get; set; }
        public int execution_time { get; set; }
        public bool success { get; set; }
    }
}
